version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.5.0
        environment:
          SESSION_SECRET: secret
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
      - image: circleci/postgres:12.0-alpine-ram
      - image: circleci/redis:5.0.6-alpine

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}

      - run: yarn install
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: yarn ci:check
